//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCC.UI.Webhost.CodeCampService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/OCC.Service.Webhost.Services")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TwitterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bio {
            get {
                return this.BioField;
            }
            set {
                if ((object.ReferenceEquals(this.BioField, value) != true)) {
                    this.BioField = value;
                    this.RaisePropertyChanged("Bio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Blog {
            get {
                return this.BlogField;
            }
            set {
                if ((object.ReferenceEquals(this.BlogField, value) != true)) {
                    this.BlogField = value;
                    this.RaisePropertyChanged("Blog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Twitter {
            get {
                return this.TwitterField;
            }
            set {
                if ((object.ReferenceEquals(this.TwitterField, value) != true)) {
                    this.TwitterField = value;
                    this.RaisePropertyChanged("Twitter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/OCC.Service.Webhost.Services")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCC.UI.Webhost.CodeCampService.Announcement[] AnnouncementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCC.UI.Webhost.CodeCampService.Person[] AttendeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCC.UI.Webhost.CodeCampService.Sponsor[] SponsorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCC.UI.Webhost.CodeCampService.Track[] TracksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TwitterHashTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCC.UI.Webhost.CodeCampService.Announcement[] Announcements {
            get {
                return this.AnnouncementsField;
            }
            set {
                if ((object.ReferenceEquals(this.AnnouncementsField, value) != true)) {
                    this.AnnouncementsField = value;
                    this.RaisePropertyChanged("Announcements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCC.UI.Webhost.CodeCampService.Person[] Attendees {
            get {
                return this.AttendeesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttendeesField, value) != true)) {
                    this.AttendeesField = value;
                    this.RaisePropertyChanged("Attendees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCC.UI.Webhost.CodeCampService.Sponsor[] Sponsors {
            get {
                return this.SponsorsField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorsField, value) != true)) {
                    this.SponsorsField = value;
                    this.RaisePropertyChanged("Sponsors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCC.UI.Webhost.CodeCampService.Track[] Tracks {
            get {
                return this.TracksField;
            }
            set {
                if ((object.ReferenceEquals(this.TracksField, value) != true)) {
                    this.TracksField = value;
                    this.RaisePropertyChanged("Tracks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TwitterHashTag {
            get {
                return this.TwitterHashTagField;
            }
            set {
                if ((object.ReferenceEquals(this.TwitterHashTagField, value) != true)) {
                    this.TwitterHashTagField = value;
                    this.RaisePropertyChanged("TwitterHashTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Announcement", Namespace="http://schemas.datacontract.org/2004/07/OCC.Service.Webhost.Services")]
    [System.SerializableAttribute()]
    public partial class Announcement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PublishDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubtitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PublishDate {
            get {
                return this.PublishDateField;
            }
            set {
                if ((this.PublishDateField.Equals(value) != true)) {
                    this.PublishDateField = value;
                    this.RaisePropertyChanged("PublishDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subtitle {
            get {
                return this.SubtitleField;
            }
            set {
                if ((object.ReferenceEquals(this.SubtitleField, value) != true)) {
                    this.SubtitleField = value;
                    this.RaisePropertyChanged("Subtitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sponsor", Namespace="http://schemas.datacontract.org/2004/07/OCC.Service.Webhost.Services")]
    [System.SerializableAttribute()]
    public partial class Sponsor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SponsorshipLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SponsorshipLevel {
            get {
                return this.SponsorshipLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorshipLevelField, value) != true)) {
                    this.SponsorshipLevelField = value;
                    this.RaisePropertyChanged("SponsorshipLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteUrl {
            get {
                return this.WebsiteUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteUrlField, value) != true)) {
                    this.WebsiteUrlField = value;
                    this.RaisePropertyChanged("WebsiteUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Track", Namespace="http://schemas.datacontract.org/2004/07/OCC.Service.Webhost.Services")]
    [System.SerializableAttribute()]
    public partial class Track : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCC.UI.Webhost.CodeCampService.Session[] SessionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCC.UI.Webhost.CodeCampService.Session[] Sessions {
            get {
                return this.SessionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionsField, value) != true)) {
                    this.SessionsField = value;
                    this.RaisePropertyChanged("Sessions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://schemas.datacontract.org/2004/07/OCC.Service.Webhost.Services")]
    [System.SerializableAttribute()]
    public partial class Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpeakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpeakerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Speaker {
            get {
                return this.SpeakerField;
            }
            set {
                if ((object.ReferenceEquals(this.SpeakerField, value) != true)) {
                    this.SpeakerField = value;
                    this.RaisePropertyChanged("Speaker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SpeakerID {
            get {
                return this.SpeakerIDField;
            }
            set {
                if ((this.SpeakerIDField.Equals(value) != true)) {
                    this.SpeakerIDField = value;
                    this.RaisePropertyChanged("SpeakerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track {
            get {
                return this.TrackField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackField, value) != true)) {
                    this.TrackField = value;
                    this.RaisePropertyChanged("Track");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Speaker", Namespace="http://schemas.datacontract.org/2004/07/OCC.Service.Webhost.Services")]
    [System.SerializableAttribute()]
    public partial class Speaker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCC.UI.Webhost.CodeCampService.Session[] SessionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TwitterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bio {
            get {
                return this.BioField;
            }
            set {
                if ((object.ReferenceEquals(this.BioField, value) != true)) {
                    this.BioField = value;
                    this.RaisePropertyChanged("Bio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Blog {
            get {
                return this.BlogField;
            }
            set {
                if ((object.ReferenceEquals(this.BlogField, value) != true)) {
                    this.BlogField = value;
                    this.RaisePropertyChanged("Blog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCC.UI.Webhost.CodeCampService.Session[] Sessions {
            get {
                return this.SessionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionsField, value) != true)) {
                    this.SessionsField = value;
                    this.RaisePropertyChanged("Sessions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Twitter {
            get {
                return this.TwitterField;
            }
            set {
                if ((object.ReferenceEquals(this.TwitterField, value) != true)) {
                    this.TwitterField = value;
                    this.RaisePropertyChanged("Twitter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://onetug.org/2012/CodeCampService", ConfigurationName="CodeCampService.ICodeCampService")]
    public interface ICodeCampService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/RegisterPerson", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/RegisterPersonResponse")]
        void RegisterPerson(OCC.UI.Webhost.CodeCampService.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/Login", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/LoginResponse")]
        OCC.UI.Webhost.CodeCampService.Person Login(OCC.UI.Webhost.CodeCampService.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/ChangePassword", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/ChangePasswordResponse")]
        void ChangePassword(int personId, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/UpdatePerson", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/UpdatePersonResponse")]
        void UpdatePerson(OCC.UI.Webhost.CodeCampService.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/DeletePerson", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/DeletePersonResponse")]
        void DeletePerson(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/FindPersonByEmail", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/FindPersonByEmailResponse" +
            "")]
        OCC.UI.Webhost.CodeCampService.Person FindPersonByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetEvents", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetEventsResponse")]
        OCC.UI.Webhost.CodeCampService.Event[] GetEvents(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/CreateEvent", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/CreateEventResponse")]
        void CreateEvent(OCC.UI.Webhost.CodeCampService.Event _event);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetEvent", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetEventResponse")]
        OCC.UI.Webhost.CodeCampService.Event GetEvent(int idEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/UpdateEvent", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/UpdateEventResponse")]
        void UpdateEvent(OCC.UI.Webhost.CodeCampService.Event _event);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetTrack", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetTrackResponse")]
        OCC.UI.Webhost.CodeCampService.Track GetTrack(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetTracks", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetTracksResponse")]
        OCC.UI.Webhost.CodeCampService.Track[] GetTracks(int idEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetTracksWithSessions", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetTracksWithSessionsResp" +
            "onse")]
        OCC.UI.Webhost.CodeCampService.Track[] GetTracksWithSessions(int idEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetSession", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetSessionResponse")]
        OCC.UI.Webhost.CodeCampService.Session GetSession(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetSpeaker", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetSpeakerResponse")]
        OCC.UI.Webhost.CodeCampService.Speaker GetSpeaker(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetAnnouncements", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetAnnouncementsResponse")]
        OCC.UI.Webhost.CodeCampService.Announcement[] GetAnnouncements(int idEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetSessions", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetSessionsResponse")]
        OCC.UI.Webhost.CodeCampService.Session[] GetSessions(int idEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetSpeakers", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetSpeakersResponse")]
        OCC.UI.Webhost.CodeCampService.Person[] GetSpeakers(int idEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetVolunteers", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetVolunteersResponse")]
        OCC.UI.Webhost.CodeCampService.Person[] GetVolunteers(int idEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://onetug.org/2012/CodeCampService/ICodeCampService/GetSponsors", ReplyAction="http://onetug.org/2012/CodeCampService/ICodeCampService/GetSponsorsResponse")]
        OCC.UI.Webhost.CodeCampService.Sponsor[] GetSponsors(int idEvent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodeCampServiceChannel : OCC.UI.Webhost.CodeCampService.ICodeCampService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodeCampServiceClient : System.ServiceModel.ClientBase<OCC.UI.Webhost.CodeCampService.ICodeCampService>, OCC.UI.Webhost.CodeCampService.ICodeCampService {
        
        public CodeCampServiceClient() {
        }
        
        public CodeCampServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodeCampServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeCampServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeCampServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterPerson(OCC.UI.Webhost.CodeCampService.Person person) {
            base.Channel.RegisterPerson(person);
        }
        
        public OCC.UI.Webhost.CodeCampService.Person Login(OCC.UI.Webhost.CodeCampService.Person person) {
            return base.Channel.Login(person);
        }
        
        public void ChangePassword(int personId, string oldPassword, string newPassword) {
            base.Channel.ChangePassword(personId, oldPassword, newPassword);
        }
        
        public void UpdatePerson(OCC.UI.Webhost.CodeCampService.Person person) {
            base.Channel.UpdatePerson(person);
        }
        
        public void DeletePerson(int personId) {
            base.Channel.DeletePerson(personId);
        }
        
        public OCC.UI.Webhost.CodeCampService.Person FindPersonByEmail(string email) {
            return base.Channel.FindPersonByEmail(email);
        }
        
        public OCC.UI.Webhost.CodeCampService.Event[] GetEvents(System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.GetEvents(fromDate, toDate);
        }
        
        public void CreateEvent(OCC.UI.Webhost.CodeCampService.Event _event) {
            base.Channel.CreateEvent(_event);
        }
        
        public OCC.UI.Webhost.CodeCampService.Event GetEvent(int idEvent) {
            return base.Channel.GetEvent(idEvent);
        }
        
        public void UpdateEvent(OCC.UI.Webhost.CodeCampService.Event _event) {
            base.Channel.UpdateEvent(_event);
        }
        
        public OCC.UI.Webhost.CodeCampService.Track GetTrack(int id) {
            return base.Channel.GetTrack(id);
        }
        
        public OCC.UI.Webhost.CodeCampService.Track[] GetTracks(int idEvent) {
            return base.Channel.GetTracks(idEvent);
        }
        
        public OCC.UI.Webhost.CodeCampService.Track[] GetTracksWithSessions(int idEvent) {
            return base.Channel.GetTracksWithSessions(idEvent);
        }
        
        public OCC.UI.Webhost.CodeCampService.Session GetSession(int id) {
            return base.Channel.GetSession(id);
        }
        
        public OCC.UI.Webhost.CodeCampService.Speaker GetSpeaker(int id) {
            return base.Channel.GetSpeaker(id);
        }
        
        public OCC.UI.Webhost.CodeCampService.Announcement[] GetAnnouncements(int idEvent) {
            return base.Channel.GetAnnouncements(idEvent);
        }
        
        public OCC.UI.Webhost.CodeCampService.Session[] GetSessions(int idEvent) {
            return base.Channel.GetSessions(idEvent);
        }
        
        public OCC.UI.Webhost.CodeCampService.Person[] GetSpeakers(int idEvent) {
            return base.Channel.GetSpeakers(idEvent);
        }
        
        public OCC.UI.Webhost.CodeCampService.Person[] GetVolunteers(int idEvent) {
            return base.Channel.GetVolunteers(idEvent);
        }
        
        public OCC.UI.Webhost.CodeCampService.Sponsor[] GetSponsors(int idEvent) {
            return base.Channel.GetSponsors(idEvent);
        }
    }
}
