//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ocpafl.org/", ConfigurationName="ServiceReference1.AutoCompleteLookupsSoap")]
    public interface AutoCompleteLookupsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/ParcelAddresses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ParcelAddresses(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/TPPAddresses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] TPPAddresses(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/NewSearchBoxLookup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] NewSearchBoxLookup(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/ParcelOwnerNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ParcelOwnerNames(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/ParcelPropertyNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ParcelPropertyNames(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/ParcelSubNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ParcelSubNames(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/TPPBusinessNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] TPPBusinessNames(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/ParcelStreetNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ParcelStreetNames(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/TPPStreetNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] TPPStreetNames(string prefixText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutoCompleteLookupsSoapChannel : WcfService1.ServiceReference1.AutoCompleteLookupsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoCompleteLookupsSoapClient : System.ServiceModel.ClientBase<WcfService1.ServiceReference1.AutoCompleteLookupsSoap>, WcfService1.ServiceReference1.AutoCompleteLookupsSoap {
        
        public AutoCompleteLookupsSoapClient() {
        }
        
        public AutoCompleteLookupsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoCompleteLookupsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoCompleteLookupsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoCompleteLookupsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] ParcelAddresses(string prefixText) {
            return base.Channel.ParcelAddresses(prefixText);
        }
        
        public string[] TPPAddresses(string prefixText) {
            return base.Channel.TPPAddresses(prefixText);
        }
        
        public string[] NewSearchBoxLookup(string prefixText) {
            return base.Channel.NewSearchBoxLookup(prefixText);
        }
        
        public string[] ParcelOwnerNames(string prefixText) {
            return base.Channel.ParcelOwnerNames(prefixText);
        }
        
        public string[] ParcelPropertyNames(string prefixText) {
            return base.Channel.ParcelPropertyNames(prefixText);
        }
        
        public string[] ParcelSubNames(string prefixText) {
            return base.Channel.ParcelSubNames(prefixText);
        }
        
        public string[] TPPBusinessNames(string prefixText) {
            return base.Channel.TPPBusinessNames(prefixText);
        }
        
        public string[] ParcelStreetNames(string prefixText) {
            return base.Channel.ParcelStreetNames(prefixText);
        }
        
        public string[] TPPStreetNames(string prefixText) {
            return base.Channel.TPPStreetNames(prefixText);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ocpafl.org/", ConfigurationName="ServiceReference1.AutoCompleteLookupsHttpGet")]
    public interface AutoCompleteLookupsHttpGet {
        
        // CODEGEN: Generating message contract since the operation ParcelAddresses is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/ParcelAddressesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/ParcelAddressesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.ParcelAddressesResponse ParcelAddresses(WcfService1.ServiceReference1.ParcelAddressesRequest request);
        
        // CODEGEN: Generating message contract since the operation TPPAddresses is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/TPPAddressesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/TPPAddressesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.TPPAddressesResponse TPPAddresses(WcfService1.ServiceReference1.TPPAddressesRequest request);
        
        // CODEGEN: Generating message contract since the operation NewSearchBoxLookup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/NewSearchBoxLookupRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/NewSearchBoxLookupResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.NewSearchBoxLookupResponse NewSearchBoxLookup(WcfService1.ServiceReference1.NewSearchBoxLookupRequest request);
        
        // CODEGEN: Generating message contract since the operation ParcelOwnerNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/ParcelOwnerNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/ParcelOwnerNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.ParcelOwnerNamesResponse ParcelOwnerNames(WcfService1.ServiceReference1.ParcelOwnerNamesRequest request);
        
        // CODEGEN: Generating message contract since the operation ParcelPropertyNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/ParcelPropertyNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/ParcelPropertyNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.ParcelPropertyNamesResponse ParcelPropertyNames(WcfService1.ServiceReference1.ParcelPropertyNamesRequest request);
        
        // CODEGEN: Generating message contract since the operation ParcelSubNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/ParcelSubNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/ParcelSubNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.ParcelSubNamesResponse ParcelSubNames(WcfService1.ServiceReference1.ParcelSubNamesRequest request);
        
        // CODEGEN: Generating message contract since the operation TPPBusinessNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/TPPBusinessNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/TPPBusinessNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.TPPBusinessNamesResponse TPPBusinessNames(WcfService1.ServiceReference1.TPPBusinessNamesRequest request);
        
        // CODEGEN: Generating message contract since the operation ParcelStreetNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/ParcelStreetNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/ParcelStreetNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.ParcelStreetNamesResponse ParcelStreetNames(WcfService1.ServiceReference1.ParcelStreetNamesRequest request);
        
        // CODEGEN: Generating message contract since the operation TPPStreetNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/TPPStreetNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpGet/TPPStreetNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.TPPStreetNamesResponse TPPStreetNames(WcfService1.ServiceReference1.TPPStreetNamesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelAddressesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public ParcelAddressesRequest() {
        }
        
        public ParcelAddressesRequest(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelAddressesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public ParcelAddressesResponse() {
        }
        
        public ParcelAddressesResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPAddressesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public TPPAddressesRequest() {
        }
        
        public TPPAddressesRequest(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPAddressesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public TPPAddressesResponse() {
        }
        
        public TPPAddressesResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewSearchBoxLookupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public NewSearchBoxLookupRequest() {
        }
        
        public NewSearchBoxLookupRequest(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewSearchBoxLookupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public NewSearchBoxLookupResponse() {
        }
        
        public NewSearchBoxLookupResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelOwnerNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public ParcelOwnerNamesRequest() {
        }
        
        public ParcelOwnerNamesRequest(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelOwnerNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public ParcelOwnerNamesResponse() {
        }
        
        public ParcelOwnerNamesResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelPropertyNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public ParcelPropertyNamesRequest() {
        }
        
        public ParcelPropertyNamesRequest(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelPropertyNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public ParcelPropertyNamesResponse() {
        }
        
        public ParcelPropertyNamesResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelSubNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public ParcelSubNamesRequest() {
        }
        
        public ParcelSubNamesRequest(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelSubNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public ParcelSubNamesResponse() {
        }
        
        public ParcelSubNamesResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPBusinessNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public TPPBusinessNamesRequest() {
        }
        
        public TPPBusinessNamesRequest(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPBusinessNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public TPPBusinessNamesResponse() {
        }
        
        public TPPBusinessNamesResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelStreetNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public ParcelStreetNamesRequest() {
        }
        
        public ParcelStreetNamesRequest(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelStreetNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public ParcelStreetNamesResponse() {
        }
        
        public ParcelStreetNamesResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPStreetNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public TPPStreetNamesRequest() {
        }
        
        public TPPStreetNamesRequest(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPStreetNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public TPPStreetNamesResponse() {
        }
        
        public TPPStreetNamesResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutoCompleteLookupsHttpGetChannel : WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoCompleteLookupsHttpGetClient : System.ServiceModel.ClientBase<WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet>, WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet {
        
        public AutoCompleteLookupsHttpGetClient() {
        }
        
        public AutoCompleteLookupsHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoCompleteLookupsHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoCompleteLookupsHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoCompleteLookupsHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.ParcelAddressesResponse WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet.ParcelAddresses(WcfService1.ServiceReference1.ParcelAddressesRequest request) {
            return base.Channel.ParcelAddresses(request);
        }
        
        public string[] ParcelAddresses(string prefixText) {
            WcfService1.ServiceReference1.ParcelAddressesRequest inValue = new WcfService1.ServiceReference1.ParcelAddressesRequest();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.ParcelAddressesResponse retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet)(this)).ParcelAddresses(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.TPPAddressesResponse WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet.TPPAddresses(WcfService1.ServiceReference1.TPPAddressesRequest request) {
            return base.Channel.TPPAddresses(request);
        }
        
        public string[] TPPAddresses(string prefixText) {
            WcfService1.ServiceReference1.TPPAddressesRequest inValue = new WcfService1.ServiceReference1.TPPAddressesRequest();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.TPPAddressesResponse retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet)(this)).TPPAddresses(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.NewSearchBoxLookupResponse WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet.NewSearchBoxLookup(WcfService1.ServiceReference1.NewSearchBoxLookupRequest request) {
            return base.Channel.NewSearchBoxLookup(request);
        }
        
        public string[] NewSearchBoxLookup(string prefixText) {
            WcfService1.ServiceReference1.NewSearchBoxLookupRequest inValue = new WcfService1.ServiceReference1.NewSearchBoxLookupRequest();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.NewSearchBoxLookupResponse retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet)(this)).NewSearchBoxLookup(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.ParcelOwnerNamesResponse WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet.ParcelOwnerNames(WcfService1.ServiceReference1.ParcelOwnerNamesRequest request) {
            return base.Channel.ParcelOwnerNames(request);
        }
        
        public string[] ParcelOwnerNames(string prefixText) {
            WcfService1.ServiceReference1.ParcelOwnerNamesRequest inValue = new WcfService1.ServiceReference1.ParcelOwnerNamesRequest();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.ParcelOwnerNamesResponse retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet)(this)).ParcelOwnerNames(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.ParcelPropertyNamesResponse WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet.ParcelPropertyNames(WcfService1.ServiceReference1.ParcelPropertyNamesRequest request) {
            return base.Channel.ParcelPropertyNames(request);
        }
        
        public string[] ParcelPropertyNames(string prefixText) {
            WcfService1.ServiceReference1.ParcelPropertyNamesRequest inValue = new WcfService1.ServiceReference1.ParcelPropertyNamesRequest();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.ParcelPropertyNamesResponse retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet)(this)).ParcelPropertyNames(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.ParcelSubNamesResponse WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet.ParcelSubNames(WcfService1.ServiceReference1.ParcelSubNamesRequest request) {
            return base.Channel.ParcelSubNames(request);
        }
        
        public string[] ParcelSubNames(string prefixText) {
            WcfService1.ServiceReference1.ParcelSubNamesRequest inValue = new WcfService1.ServiceReference1.ParcelSubNamesRequest();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.ParcelSubNamesResponse retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet)(this)).ParcelSubNames(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.TPPBusinessNamesResponse WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet.TPPBusinessNames(WcfService1.ServiceReference1.TPPBusinessNamesRequest request) {
            return base.Channel.TPPBusinessNames(request);
        }
        
        public string[] TPPBusinessNames(string prefixText) {
            WcfService1.ServiceReference1.TPPBusinessNamesRequest inValue = new WcfService1.ServiceReference1.TPPBusinessNamesRequest();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.TPPBusinessNamesResponse retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet)(this)).TPPBusinessNames(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.ParcelStreetNamesResponse WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet.ParcelStreetNames(WcfService1.ServiceReference1.ParcelStreetNamesRequest request) {
            return base.Channel.ParcelStreetNames(request);
        }
        
        public string[] ParcelStreetNames(string prefixText) {
            WcfService1.ServiceReference1.ParcelStreetNamesRequest inValue = new WcfService1.ServiceReference1.ParcelStreetNamesRequest();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.ParcelStreetNamesResponse retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet)(this)).ParcelStreetNames(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.TPPStreetNamesResponse WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet.TPPStreetNames(WcfService1.ServiceReference1.TPPStreetNamesRequest request) {
            return base.Channel.TPPStreetNames(request);
        }
        
        public string[] TPPStreetNames(string prefixText) {
            WcfService1.ServiceReference1.TPPStreetNamesRequest inValue = new WcfService1.ServiceReference1.TPPStreetNamesRequest();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.TPPStreetNamesResponse retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpGet)(this)).TPPStreetNames(inValue);
            return retVal.ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ocpafl.org/", ConfigurationName="ServiceReference1.AutoCompleteLookupsHttpPost")]
    public interface AutoCompleteLookupsHttpPost {
        
        // CODEGEN: Generating message contract since the operation ParcelAddresses is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/ParcelAddressesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/ParcelAddressesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.ParcelAddressesResponse1 ParcelAddresses(WcfService1.ServiceReference1.ParcelAddressesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation TPPAddresses is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/TPPAddressesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/TPPAddressesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.TPPAddressesResponse1 TPPAddresses(WcfService1.ServiceReference1.TPPAddressesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation NewSearchBoxLookup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/NewSearchBoxLookupRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/NewSearchBoxLookupResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.NewSearchBoxLookupResponse1 NewSearchBoxLookup(WcfService1.ServiceReference1.NewSearchBoxLookupRequest1 request);
        
        // CODEGEN: Generating message contract since the operation ParcelOwnerNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/ParcelOwnerNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/ParcelOwnerNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.ParcelOwnerNamesResponse1 ParcelOwnerNames(WcfService1.ServiceReference1.ParcelOwnerNamesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation ParcelPropertyNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/ParcelPropertyNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/ParcelPropertyNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.ParcelPropertyNamesResponse1 ParcelPropertyNames(WcfService1.ServiceReference1.ParcelPropertyNamesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation ParcelSubNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/ParcelSubNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/ParcelSubNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.ParcelSubNamesResponse1 ParcelSubNames(WcfService1.ServiceReference1.ParcelSubNamesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation TPPBusinessNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/TPPBusinessNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/TPPBusinessNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.TPPBusinessNamesResponse1 TPPBusinessNames(WcfService1.ServiceReference1.TPPBusinessNamesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation ParcelStreetNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/ParcelStreetNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/ParcelStreetNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.ParcelStreetNamesResponse1 ParcelStreetNames(WcfService1.ServiceReference1.ParcelStreetNamesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation TPPStreetNames is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/TPPStreetNamesRequest", ReplyAction="http://www.ocpafl.org/AutoCompleteLookupsHttpPost/TPPStreetNamesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WcfService1.ServiceReference1.TPPStreetNamesResponse1 TPPStreetNames(WcfService1.ServiceReference1.TPPStreetNamesRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelAddressesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public ParcelAddressesRequest1() {
        }
        
        public ParcelAddressesRequest1(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelAddressesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public ParcelAddressesResponse1() {
        }
        
        public ParcelAddressesResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPAddressesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public TPPAddressesRequest1() {
        }
        
        public TPPAddressesRequest1(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPAddressesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public TPPAddressesResponse1() {
        }
        
        public TPPAddressesResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewSearchBoxLookupRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public NewSearchBoxLookupRequest1() {
        }
        
        public NewSearchBoxLookupRequest1(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewSearchBoxLookupResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public NewSearchBoxLookupResponse1() {
        }
        
        public NewSearchBoxLookupResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelOwnerNamesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public ParcelOwnerNamesRequest1() {
        }
        
        public ParcelOwnerNamesRequest1(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelOwnerNamesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public ParcelOwnerNamesResponse1() {
        }
        
        public ParcelOwnerNamesResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelPropertyNamesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public ParcelPropertyNamesRequest1() {
        }
        
        public ParcelPropertyNamesRequest1(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelPropertyNamesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public ParcelPropertyNamesResponse1() {
        }
        
        public ParcelPropertyNamesResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelSubNamesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public ParcelSubNamesRequest1() {
        }
        
        public ParcelSubNamesRequest1(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelSubNamesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public ParcelSubNamesResponse1() {
        }
        
        public ParcelSubNamesResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPBusinessNamesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public TPPBusinessNamesRequest1() {
        }
        
        public TPPBusinessNamesRequest1(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPBusinessNamesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public TPPBusinessNamesResponse1() {
        }
        
        public TPPBusinessNamesResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelStreetNamesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public ParcelStreetNamesRequest1() {
        }
        
        public ParcelStreetNamesRequest1(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParcelStreetNamesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public ParcelStreetNamesResponse1() {
        }
        
        public ParcelStreetNamesResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPStreetNamesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string prefixText;
        
        public TPPStreetNamesRequest1() {
        }
        
        public TPPStreetNamesRequest1(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPPStreetNamesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ocpafl.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public TPPStreetNamesResponse1() {
        }
        
        public TPPStreetNamesResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutoCompleteLookupsHttpPostChannel : WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoCompleteLookupsHttpPostClient : System.ServiceModel.ClientBase<WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost>, WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost {
        
        public AutoCompleteLookupsHttpPostClient() {
        }
        
        public AutoCompleteLookupsHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoCompleteLookupsHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoCompleteLookupsHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoCompleteLookupsHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.ParcelAddressesResponse1 WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost.ParcelAddresses(WcfService1.ServiceReference1.ParcelAddressesRequest1 request) {
            return base.Channel.ParcelAddresses(request);
        }
        
        public string[] ParcelAddresses(string prefixText) {
            WcfService1.ServiceReference1.ParcelAddressesRequest1 inValue = new WcfService1.ServiceReference1.ParcelAddressesRequest1();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.ParcelAddressesResponse1 retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost)(this)).ParcelAddresses(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.TPPAddressesResponse1 WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost.TPPAddresses(WcfService1.ServiceReference1.TPPAddressesRequest1 request) {
            return base.Channel.TPPAddresses(request);
        }
        
        public string[] TPPAddresses(string prefixText) {
            WcfService1.ServiceReference1.TPPAddressesRequest1 inValue = new WcfService1.ServiceReference1.TPPAddressesRequest1();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.TPPAddressesResponse1 retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost)(this)).TPPAddresses(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.NewSearchBoxLookupResponse1 WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost.NewSearchBoxLookup(WcfService1.ServiceReference1.NewSearchBoxLookupRequest1 request) {
            return base.Channel.NewSearchBoxLookup(request);
        }
        
        public string[] NewSearchBoxLookup(string prefixText) {
            WcfService1.ServiceReference1.NewSearchBoxLookupRequest1 inValue = new WcfService1.ServiceReference1.NewSearchBoxLookupRequest1();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.NewSearchBoxLookupResponse1 retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost)(this)).NewSearchBoxLookup(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.ParcelOwnerNamesResponse1 WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost.ParcelOwnerNames(WcfService1.ServiceReference1.ParcelOwnerNamesRequest1 request) {
            return base.Channel.ParcelOwnerNames(request);
        }
        
        public string[] ParcelOwnerNames(string prefixText) {
            WcfService1.ServiceReference1.ParcelOwnerNamesRequest1 inValue = new WcfService1.ServiceReference1.ParcelOwnerNamesRequest1();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.ParcelOwnerNamesResponse1 retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost)(this)).ParcelOwnerNames(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.ParcelPropertyNamesResponse1 WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost.ParcelPropertyNames(WcfService1.ServiceReference1.ParcelPropertyNamesRequest1 request) {
            return base.Channel.ParcelPropertyNames(request);
        }
        
        public string[] ParcelPropertyNames(string prefixText) {
            WcfService1.ServiceReference1.ParcelPropertyNamesRequest1 inValue = new WcfService1.ServiceReference1.ParcelPropertyNamesRequest1();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.ParcelPropertyNamesResponse1 retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost)(this)).ParcelPropertyNames(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.ParcelSubNamesResponse1 WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost.ParcelSubNames(WcfService1.ServiceReference1.ParcelSubNamesRequest1 request) {
            return base.Channel.ParcelSubNames(request);
        }
        
        public string[] ParcelSubNames(string prefixText) {
            WcfService1.ServiceReference1.ParcelSubNamesRequest1 inValue = new WcfService1.ServiceReference1.ParcelSubNamesRequest1();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.ParcelSubNamesResponse1 retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost)(this)).ParcelSubNames(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.TPPBusinessNamesResponse1 WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost.TPPBusinessNames(WcfService1.ServiceReference1.TPPBusinessNamesRequest1 request) {
            return base.Channel.TPPBusinessNames(request);
        }
        
        public string[] TPPBusinessNames(string prefixText) {
            WcfService1.ServiceReference1.TPPBusinessNamesRequest1 inValue = new WcfService1.ServiceReference1.TPPBusinessNamesRequest1();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.TPPBusinessNamesResponse1 retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost)(this)).TPPBusinessNames(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.ParcelStreetNamesResponse1 WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost.ParcelStreetNames(WcfService1.ServiceReference1.ParcelStreetNamesRequest1 request) {
            return base.Channel.ParcelStreetNames(request);
        }
        
        public string[] ParcelStreetNames(string prefixText) {
            WcfService1.ServiceReference1.ParcelStreetNamesRequest1 inValue = new WcfService1.ServiceReference1.ParcelStreetNamesRequest1();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.ParcelStreetNamesResponse1 retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost)(this)).ParcelStreetNames(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfService1.ServiceReference1.TPPStreetNamesResponse1 WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost.TPPStreetNames(WcfService1.ServiceReference1.TPPStreetNamesRequest1 request) {
            return base.Channel.TPPStreetNames(request);
        }
        
        public string[] TPPStreetNames(string prefixText) {
            WcfService1.ServiceReference1.TPPStreetNamesRequest1 inValue = new WcfService1.ServiceReference1.TPPStreetNamesRequest1();
            inValue.prefixText = prefixText;
            WcfService1.ServiceReference1.TPPStreetNamesResponse1 retVal = ((WcfService1.ServiceReference1.AutoCompleteLookupsHttpPost)(this)).TPPStreetNames(inValue);
            return retVal.ArrayOfString;
        }
    }
}
